name: 'Use Proxy to SSH and Rsync'
description: 'Github -> proxy -> server'
author: 'specerxi'
branding:
  icon: 'copy'
  color: 'blue'
inputs:
  rsync_flags:
    description: 'you know'
  dst_host:
    description: 'online host'
  dst_port:
    description: 'online port'
    default: 22
  dst_user:
    description: 'online user'
  proxy_host:
    description: ''
  proxy_port:
    description: ''
    default: 22
  proxy_user:
    description: ''
  src_file:
    description: 'src file name'
  proxy_file_path:
    description: 'temporary save path'
  dst_file_path:
    description: 'online save path'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  ssh_before:
    description: 'execute commands before rsync on proxy host'
  ssh_after:
    description: 'execute commands after rsync on proxy host'
runs:
  using: 'docker'
  image: 'Dockerfile'
