name: 'SSH and Rsync Setup'
description: 'Executing remote ssh and rsync commands'
author: 'specerxi'
branding:
  icon: 'copy'
  color: 'blue'
inputs:
  rsync_flags:
    description: 'you know'
  dst_host:
    description: 'ssh remote host'
  dst_port:
    description: 'ssh remote port'
    default: 22
  dst_user:
    description: 'ssh user'
  board_host:
    description: 'ssh board host'
  board_port:
    description: 'ssh board port'
    default: 22
  board_user:
    description: 'ssh board user'
  file_name:
    description: 'src file name'
  board_file_path:
    description: 'temporary save path'
  dst_file_path:
    description: 'remote save path'
  board_script:
    description: 'exec script in board to effect dst host'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  ssh_before:
    description: 'execute commands before rsync'
  ssh_after:
    description: 'execute commands after rsync'
runs:
  using: 'docker'
  image: 'Dockerfile'
